export const jobs = [
    {
        id: 1,
        title: "Software Engineer",
        company: "ABC Tech",
        location: "New York",
        salary: "$100,000",
        requirements: ["Bachelor's degree in Computer Science", "Experience with JavaScript"],
        description: "We are seeking a skilled Software Engineer to join our team and develop high-quality software solutions. You will work on various projects and collaborate with a talented team of developers.",
    },
    {
        id: 2,
        title: "Marketing Specialist",
        company: "XYZ Inc.",
        location: "San Francisco",
        salary: "$80,000",
        requirements: ["Bachelor's degree in Marketing", "Experience with social media marketing"],
        description: "As a Marketing Specialist, you will be responsible for creating and implementing marketing campaigns, managing social media accounts, and analyzing campaign performance. Join our dynamic team and make an impact in the digital marketing world.",
    },
    {
        id: 3,
        title: "Graphic Designer",
        company: "Design Co.",
        location: "London",
        salary: "$70,000",
        requirements: ["Proficiency in Adobe Creative Suite", "Experience in UI/UX design"],
        description: "Design Co. is looking for a talented Graphic Designer to create visually stunning designs for our clients. If you have a keen eye for aesthetics and a passion for design, this is the perfect opportunity for you.",
    },
    {
        id: 4,
        title: "Data Scientist",
        company: "Insights Lab",
        location: "Seattle",
        salary: "$120,000",
        requirements: ["Master's degree in Statistics or related field", "Experience with machine learning algorithms"],
        description: "Insights Lab is seeking a talented Data Scientist to analyze and interpret complex data sets. You will develop innovative machine learning models and work closely with cross-functional teams to deliver data-driven solutions.",
    },
    {
        id: 5,
        title: "Product Manager",
        company: "Tech Innovators",
        location: "San Francisco",
        salary: "$110,000",
        requirements: ["Bachelor's degree in Business or related field", "Experience in product management"],
        description: "Tech Innovators is looking for a motivated Product Manager to drive the development and launch of new products. Join our team and play a key role in shaping the future of technology.",
    },
    {
        id: 6,
        title: "UX/UI Designer",
        company: "Creative Solutions",
        location: "Berlin",
        salary: "$90,000",
        requirements: ["Strong portfolio showcasing UX/UI design skills", "Experience with prototyping tools"],
        description: "Creative Solutions is seeking a talented UX/UI Designer to create intuitive and engaging user experiences. You will collaborate with cross-functional teams to design and iterate on user interfaces for our digital products.",
    },
    {
        id: 7,
        title: "Sales Representative",
        company: "Global Solutions",
        location: "Tokyo",
        salary: "$85,000",
        requirements: ["Excellent communication and negotiation skills", "Experience in B2B sales"],
        description: "Join our sales team at Global Solutions and help drive business growth through effective relationship building and sales strategies. If you have a passion for sales and a global mindset, this is the perfect opportunity for you.",
    },
    {
        id: 8,
        title: "Data Analyst",
        company: "Insightful Analytics",
        location: "Chicago",
        salary: "$75,000",
        requirements: ["Strong analytical skills", "Proficiency in SQL"],
        description: "Join our team as a Data Analyst and help analyze complex data sets to uncover valuable insights. You will work closely with stakeholders to provide data-driven recommendations and contribute to the growth of our organization.",
    }
]